# -*- coding: utf-8 -*-
"""cloning Git .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i620FvTPkHKSx8J2DY4eepSec5LVnWoW
"""

#cloning from github
!git config --global user.name "username"
!git config --global user.email "your email"
!git config --global user.password "password"

token = "token"
username = "username"
repo = "repository"

!git clone http://{token}@github.com/{username}/{repo}
