# -*- coding: utf-8 -*-
"""cloning Git .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i620FvTPkHKSx8J2DY4eepSec5LVnWoW
"""

#cloning from github
!git config --global user.name "amirreza82mh"
!git config --global user.email "amirreza82mh@gmail.com"
!git config --global user.password "159683724Am@"

token = "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"
username = "amirreza82mh"
repo = "colab"

!git clone http://{token}@github.com/{username}/{repo}