# -*- coding: utf-8 -*-
"""project006.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNzXtyzBPyAY96bVbJZq0_QOiLga67CL

# **String :)**
"""

s = 'abcdef'
print(s[3])       #d
print(s[1 : 4])   #bcd
print(s[1 : -1])  #bcde
print(s[ : 4])    #abcd 
print(s[2 : ])    #cdef
print(s[ :: -1])   #fedcba

print(ord('a'))
print(chr(65))

print('\n====================\n')

s = 'amirrezamehrabani'
print(s.islower())
print(s.isupper())
print('a' in s)
print('o' not in s)
print(s.isalpha())
print(s.isalnum())
print(s.isdigit())

print('\n====================\n')

s = 'amirreza82'
print(s.isalnum())
print(s.isalpha())
print(s.isdigit())

print('\n====================\n')

s = '123456789'
print(s.isalnum())
print(s.isalpha())
print(s.isdigit())

print('\n====================\n')

s = '\t'
print(s.isspace())

#example
s = '1a2bc3def4'
k = 0
for ch in s:
  if ch.isdigit() == True:
    k += int(ch)

print('k = %i' %k)